version: '3.8'
services:
  research-api:
    build:     
      context: .
      dockerfile: ./src/ResearchDatabase.API/Dockerfile
    ports:
      - "8080:8080"
      - "5000:80" 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080;http://+:80
    depends_on:
      - sqlserver
    command: /bin/bash -c "until nc -z sqlserver 1434; do echo waiting for sqlserver; sleep 1; done; dotnet ResearchDatabase.API.dll"

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: NewPassword123
      ACCEPT_EULA: Y
    ports:
      - "1434:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql/data
    user: root

volumes:
  sqlserver-data: